# Generated by Django 4.2.10 on 2025-03-26 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("discount_ratio", models.FloatField(default=0)),
                ("in_stock", models.BooleanField(default=False)),
                ("images", models.JSONField(default=list)),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(default="success", max_length=20)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="ProductLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.URLField(max_length=500)),
                ("lc_last_modification", models.DateTimeField(blank=True, null=True)),
                (
                    "change_frequence",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("priority", models.FloatField(blank=True, null=True)),
                ("system_last_modification", models.DateTimeField(auto_now=True)),
                ("batch_id", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Product Location",
                "verbose_name_plural": "Product Locations",
            },
        ),
        migrations.CreateModel(
            name="ProductSitemap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.URLField(max_length=500)),
                ("last_modification", models.DateTimeField(blank=True, null=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product Sitemap",
                "verbose_name_plural": "Product Sitemaps",
            },
        ),
        migrations.CreateModel(
            name="ProductSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size_name", models.CharField(max_length=50)),
                ("size_id", models.CharField(max_length=50)),
                ("size_general_stock", models.IntegerField(default=0)),
                ("product_option_size_reference", models.IntegerField()),
                ("barcode_list", models.JSONField(default=list)),
                ("size_city_stock", models.JSONField(default=dict)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="lcwaikiki.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Size",
                "verbose_name_plural": "Product Sizes",
            },
        ),
    ]
