# Generated by Django 3.1.12 on 2025-03-26 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcwaikiki', '0002_auto_20250326_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.JSONField(default=dict, help_text='Structured size information'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_ratio',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('error', 'Error')], default='success', max_length=20),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'color'], name='lcwaikiki_p_categor_476fe0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='lcwaikiki_p_price_895617_idx'),
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
